# Generated by Django 5.0.14 on 2026-03-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='user message')),
                ('ai_response', models.TextField(verbose_name='AI response')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='tokens used')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_references', to='places.touristplace', verbose_name='related place')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
    ]
