# Generated by Django 5.0.14 on 2026-03-12 05:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('location', models.CharField(db_index=True, max_length=300, verbose_name='location')),
                ('state', models.CharField(db_index=True, default='Tennessee', max_length=100, verbose_name='state')),
                ('category', models.CharField(choices=[('nature', 'Nature & Parks'), ('history', 'Historical Sites'), ('culture', 'Culture & Arts'), ('adventure', 'Adventure & Sports'), ('food', 'Food & Cuisine'), ('entertainment', 'Entertainment'), ('religious', 'Religious Sites'), ('shopping', 'Shopping'), ('other', 'Other')], db_index=True, default='other', max_length=30, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='short description')),
                ('rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/%Y/%m/', verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='image alt text')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if free.', max_digits=8, null=True, verbose_name='entry fee ($)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_places', to=settings.AUTH_USER_MODEL, verbose_name='favorited by')),
            ],
            options={
                'verbose_name': 'tourist place',
                'verbose_name_plural': 'tourist places',
                'ordering': ['-is_featured', '-rating', 'name'],
                'indexes': [models.Index(fields=['name', 'location'], name='places_tour_name_48c43b_idx'), models.Index(fields=['category', 'is_active'], name='places_tour_categor_f8f1a6_idx'), models.Index(fields=['is_featured', 'rating'], name='places_tour_is_feat_89cee1_idx')],
            },
        ),
    ]
