# Generated by Django 5.0.14 on 2026-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='state',
            field=models.CharField(db_index=True, default='Tamil Nadu', max_length=100, verbose_name='state'),
        ),
    ]
