# Generated by Django 5.0.14 on 2026-03-12 08:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_touristplace_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='touristplace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_place_name_ci'),
        ),
    ]
